
--TANUJA
--creating customers
create user C101 identified by Customer_12345;
GRANT CREATE SESSION TO C101;
GRANT UNLIMITED TABLESPACE TO C101; 

create user C102 identified by Customer_12345;
GRANT CREATE SESSION TO C102;
GRANT UNLIMITED TABLESPACE TO C102; 

create user C103 identified by Customer_12345;
GRANT CREATE SESSION TO C103;
GRANT UNLIMITED TABLESPACE TO C103; 

create user C104 identified by Customer_12345;
GRANT CREATE SESSION TO C104;
GRANT UNLIMITED TABLESPACE TO C104;

create user C105 identified by Customer_12345;
GRANT CREATE SESSION TO C105;
GRANT UNLIMITED TABLESPACE TO C105; 

create user C106 identified by Customer_12345;
GRANT CREATE SESSION TO C106;
GRANT UNLIMITED TABLESPACE TO C106; 


--creating store managers
create user Costco_SMGR101 identified by Manager_12345;
GRANT CREATE SESSION TO Costco_SMGR101;
GRANT UNLIMITED TABLESPACE TO Costco_SMGR101; 

create user Target_SMGR102 identified by Manager_12345;
GRANT CREATE SESSION TO Target_SMGR102;
GRANT UNLIMITED TABLESPACE TO Target_SMGR102;

create user Walmart_SMGR103 identified by Manager_12345;
GRANT CREATE SESSION TO Walmart_SMGR103;
GRANT UNLIMITED TABLESPACE TO Walmart_SMGR103; 

create user SamsClub_SMGR104 identified by Manager_12345;
GRANT CREATE SESSION TO SamsClub_SMGR104;
GRANT UNLIMITED TABLESPACE TO SamsClub_SMGR104; 

create user WholeFoods_SMGR105 identified by Manager_12345;
GRANT CREATE SESSION TO WholeFoods_SMGR105;
GRANT UNLIMITED TABLESPACE TO WholeFoods_SMGR105; 

create user Kroger_SMGR106 identified by Manager_12345;
GRANT CREATE SESSION TO Kroger_SMGR106;
GRANT UNLIMITED TABLESPACE TO Kroger_SMGR106; 

create user Publix_SMGR107 identified by Manager_12345;
GRANT CREATE SESSION TO Publix_SMGR107;
GRANT UNLIMITED TABLESPACE TO Publix_SMGR107; 

create user DollarGeneral_SMGR108 identified by Manager_12345;
GRANT CREATE SESSION TO DollarGeneral_SMGR108;
GRANT UNLIMITED TABLESPACE TO DollarGeneral_SMGR108; 




--creating users by our names 
CREATE USER Ashvini IDENTIFIED BY Art_123456789;
GRANT CREATE SESSION TO Ashvini;
GRANT CREATE TABLE TO Ashvini;
GRANT UNLIMITED TABLESPACE TO Ashvini; 


CREATE USER Ritwik IDENTIFIED BY Art_123456789;
GRANT CREATE SESSION TO Ritwik;
GRANT CREATE TABLE TO Ritwik;
GRANT UNLIMITED TABLESPACE TO Ritwik; 


CREATE USER Tanuja IDENTIFIED BY Art_123456789;
GRANT CREATE SESSION TO Tanuja;
GRANT CREATE TABLE TO Tanuja;
GRANT UNLIMITED TABLESPACE TO Tanuja; 
GRANT CREATE SYNONYM TO Tanuja;

--COMMON USER CREATED TO CONTINUE THE WORK

CREATE USER Art IDENTIFIED BY Pro_dmdd_2023;
GRANT CREATE SESSION TO Art;
GRANT CREATE TABLE,CREATE SEQUENCE,CREATE PROCEDURE, CREATE VIEW TO Art;
GRANT UNLIMITED TABLESPACE TO Art;

COMMIT;

